services:
  agent:
    build: .
    networks:
      ctfwatch-net:
        aliases:
          - ctfwatch
    volumes:
      - ./config.json:/etc/ctfwatch/config.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    # REMOVE LATER ---
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # -----------------

networks:
  ctfwatch-net:
    external: true